//! M6 local domains: one shared Caddy router on host ports 80/443 that maps
//! `http(s)://<slug>.test` to each site's `localhost:<port>`.
//!
//! Design decisions:
//! - TLD is `.test` (RFC 2606, reserved for testing): no collision with
//!   LocalWP's `.local`, and it resolves consistently across browsers and OS
//!   resolvers. Unlike `.localhost`, nothing auto-resolves it, so LocalKit
//!   manages a marked block (`# BEGIN/END LOCALKIT`) in the OS hosts file —
//!   edits require a one-time elevated approval per change (UAC / sudo).
//! - The router proxies to `host.docker.internal:<site port>`, so existing
//!   site compose projects are untouched (no shared Docker network).
//! - Caddy serves BOTH plain http and https (`tls internal`, local CA); there
//!   is no http→https redirect so users who haven't trusted the CA yet get a
//!   clean http path. "Trusted" is tracked by recording the install command's
//!   success in the settings table — we don't probe OS trust stores.

use serde::Serialize;
use std::path::{Path, PathBuf};

use crate::{docker, site::Site, wordpress, AppState};

pub const TLD: &str = "test";
const KEY_ENABLED: &str = "domains_enabled";
const KEY_CA_TRUSTED: &str = "router_ca_trusted";
const KEY_LAST_ERROR: &str = "router_last_error";
/// Path of Caddy's local-CA root cert inside the container.
const CA_CERT_CONTAINER_PATH: &str = "/data/caddy/pki/authorities/local/root.crt";
/// Managed-block markers in the OS hosts file.
const HOSTS_BEGIN: &str = "# BEGIN LOCALKIT";
const HOSTS_END: &str = "# END LOCALKIT";

#[derive(Debug, Clone, Serialize)]
pub struct RouterStatus {
    pub enabled: bool,
    pub running: bool,
    pub ca_trusted: bool,
    pub error: Option<String>,
}

pub fn router_dir(data_dir: &Path) -> PathBuf {
    data_dir.join("router")
}

/// The URL a site is reachable at through the router.
pub fn site_url(slug: &str, ca_trusted: bool) -> String {
    let scheme = if ca_trusted { "https" } else { "http" };
    format!("{scheme}://{slug}.{TLD}")
}

fn render_compose() -> String {
    r#"name: localkit-router

services:
  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    # Route to sites via their published host ports — no shared network,
    # no changes to per-site compose projects.
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data

volumes:
  caddy-data:
"#
    .to_string()
}

fn render_caddyfile(sites: &[Site]) -> String {
    let mut out = String::from("# Generated by LocalKit — do not edit by hand.\n\n");
    for site in sites {
        out.push_str(&format!(
            "http://{slug}.{TLD} {{\n\treverse_proxy host.docker.internal:{port}\n}}\n\n\
             https://{slug}.{TLD} {{\n\ttls internal\n\treverse_proxy host.docker.internal:{port}\n}}\n\n",
            slug = site.slug,
            port = site.port,
        ));
    }
    out
}

/// Write the router compose project + Caddyfile for the given sites.
fn write_files(data_dir: &Path, sites: &[Site]) -> Result<PathBuf, String> {
    let dir = router_dir(data_dir);
    std::fs::create_dir_all(&dir).map_err(|e| format!("failed to create router directory: {e}"))?;
    std::fs::write(dir.join("docker-compose.yml"), render_compose())
        .map_err(|e| format!("failed to write router docker-compose.yml: {e}"))?;
    std::fs::write(dir.join("Caddyfile"), render_caddyfile(sites))
        .map_err(|e| format!("failed to write Caddyfile: {e}"))?;
    Ok(dir)
}

/// Reload Caddy's config in the running container; fall back to a restart.
async fn reload(dir: &Path) -> Result<(), String> {
    if docker::compose_exec(dir, "caddy", &["caddy", "reload", "--config", "/etc/caddy/Caddyfile"])
        .await
        .is_ok()
    {
        return Ok(());
    }
    docker::compose_restart(dir).await
}

/// Add a "what's probably holding the port" hint to bind failures.
fn port_conflict_hint(err: &str) -> String {
    let lower = err.to_lowercase();
    if lower.contains("port is already allocated")
        || lower.contains("address already in use")
        || lower.contains("bind")
        || lower.contains("permission denied") && lower.contains("80")
    {
        format!(
            "Could not start the local-domains router: ports 80/443 appear to be in use \
             by another program (LocalWP's router, IIS, Skype, or another web server). \
             Stop whatever is bound to port 80/443 and try again.\n\nDetails: {err}"
        )
    } else {
        format!("Could not start the local-domains router: {err}")
    }
}

// ---------------------------------------------------------------------------
// Hosts file management (`.test` does not auto-resolve — browsers AND the OS
// resolver need `127.0.0.1 <slug>.test` entries). Edits are made inside a
// marked block and require elevation (UAC / administrator password).
// ---------------------------------------------------------------------------

#[cfg(target_os = "windows")]
fn hosts_file_path() -> PathBuf {
    let root = std::env::var("SystemRoot").unwrap_or_else(|_| r"C:\Windows".into());
    PathBuf::from(root).join(r"System32\drivers\etc\hosts")
}

#[cfg(not(target_os = "windows"))]
fn hosts_file_path() -> PathBuf {
    PathBuf::from("/etc/hosts")
}

/// Insert or replace the LocalKit managed block in hosts-file `content`.
/// An empty `slugs` list removes the block. Pure (and unit-tested) — all
/// elevation/IO lives in `sync_hosts`.
fn update_hosts_content(content: &str, slugs: &[String]) -> String {
    let eol = if content.contains("\r\n") { "\r\n" } else { "\n" };
    let mut lines: Vec<String> = content
        .split('\n')
        .map(|l| l.trim_end_matches('\r').to_string())
        .collect();
    while matches!(lines.last(), Some(l) if l.is_empty()) {
        lines.pop();
    }

    let begin = lines.iter().position(|l| l.trim() == HOSTS_BEGIN);
    let end = lines.iter().position(|l| l.trim() == HOSTS_END);
    let had_block = matches!((begin, end), (Some(b), Some(e)) if b <= e);
    if let (Some(b), Some(e)) = (begin, end) {
        if b <= e {
            lines.drain(b..=e);
            // Also drop a single blank separator line left right before it.
            if b > 0 && matches!(lines.get(b - 1), Some(l) if l.is_empty()) {
                lines.remove(b - 1);
            }
        }
    }

    if slugs.is_empty() {
        if !had_block {
            return content.to_string(); // nothing to do — byte-identical
        }
    } else {
        if !lines.is_empty() {
            lines.push(String::new());
        }
        lines.push(HOSTS_BEGIN.to_string());
        for slug in slugs {
            lines.push(format!("127.0.0.1  {slug}.{TLD}"));
        }
        lines.push(HOSTS_END.to_string());
    }

    let mut out = lines.join(eol);
    if !out.is_empty() {
        out.push_str(eol);
    }
    out
}

/// Map an elevated-helper failure to a user-displayable message.
fn elevation_error(detail: &str) -> String {
    let lower = detail.to_lowercase();
    if lower.contains("canceled") || lower.contains("cancelled") || lower.contains("(-128)") {
        "Administrator approval is needed to manage hosts entries, and the approval \
         prompt was declined. Local domains were not enabled."
            .into()
    } else {
        format!(
            "Could not update the hosts file ({}): {}",
            hosts_file_path().display(),
            detail.trim().chars().take(300).collect::<String>()
        )
    }
}

/// Write `content` over the OS hosts file via an elevated one-shot helper:
/// Windows: UAC (`Start-Process -Verb RunAs`), macOS: `osascript … with
/// administrator privileges`, Linux: `pkexec` (with a sudo fallback message).
async fn write_hosts_elevated(content: &str) -> Result<(), String> {
    let id = uuid::Uuid::new_v4().simple().to_string();
    let tmp = std::env::temp_dir().join(format!("localkit-hosts-{id}.txt"));
    std::fs::write(&tmp, content).map_err(|e| format!("failed to stage hosts file: {e}"))?;
    let hosts = hosts_file_path();

    #[cfg(target_os = "windows")]
    let result = {
        // A tiny .bat keeps PowerShell quoting sane; RunAs triggers UAC.
        let bat = std::env::temp_dir().join(format!("localkit-hosts-{id}.bat"));
        let script = format!(
            "@echo off\r\ncopy /y \"{}\" \"{}\" >nul\r\n",
            tmp.display(),
            hosts.display()
        );
        std::fs::write(&bat, script).map_err(|e| format!("failed to stage hosts helper: {e}"))?;
        let ps = format!(
            "$ErrorActionPreference='Stop'; try {{ \
             $p = Start-Process -FilePath cmd.exe -ArgumentList '/c','\"{}\"' \
             -Verb RunAs -Wait -PassThru -WindowStyle Hidden; exit $p.ExitCode \
             }} catch {{ Write-Error $_; exit 1 }}",
            bat.display()
        );
        let out = docker::no_window(
            tokio::process::Command::new("powershell").args(["-NoProfile", "-Command", &ps]),
        )
        .output()
        .await;
        let _ = std::fs::remove_file(&bat);
        out
    };
    #[cfg(target_os = "macos")]
    let result = {
        let script = format!(
            "do shell script \"cp '{}' '{}'\" with administrator privileges",
            tmp.display(),
            hosts.display()
        );
        tokio::process::Command::new("osascript")
            .args(["-e", &script])
            .output()
            .await
    };
    #[cfg(all(unix, not(target_os = "macos")))]
    let result = {
        match tokio::process::Command::new("pkexec")
            .arg("cp")
            .arg(&tmp)
            .arg(&hosts)
            .output()
            .await
        {
            Err(_) => {
                // No pkexec: leave the staged file and tell the user exactly
                // what to run.
                let _ = std::fs::remove_file(&tmp);
                let staged = std::env::temp_dir().join(format!("localkit-hosts-{id}.txt"));
                std::fs::write(&staged, content).ok();
                return Err(format!(
                    "Could not update {} automatically (pkexec not found). \
                     Run this command yourself, then toggle local domains again:\n\n  sudo cp '{}' {}",
                    hosts.display(),
                    staged.display(),
                    hosts.display()
                ));
            }
            ok => ok,
        }
    };

    let _ = std::fs::remove_file(&tmp);
    match result {
        Ok(out) if out.status.success() => Ok(()),
        Ok(out) => Err(elevation_error(&format!(
            "{}{}",
            String::from_utf8_lossy(&out.stderr),
            String::from_utf8_lossy(&out.stdout)
        ))),
        Err(e) => Err(elevation_error(&e.to_string())),
    }
}

/// Reconcile the managed hosts block with `slugs` (empty = remove block).
/// Reads the file unprivileged; only the write is elevated. Verifies the
/// write afterwards so a silently-failed elevation is still reported.
async fn sync_hosts(slugs: &[String]) -> Result<(), String> {
    let path = hosts_file_path();
    let current = std::fs::read_to_string(&path).unwrap_or_default();
    let desired = update_hosts_content(&current, slugs);
    if desired == current {
        return Ok(());
    }
    write_hosts_elevated(&desired).await?;
    let after = std::fs::read_to_string(&path).unwrap_or_default();
    if after == desired {
        Ok(())
    } else {
        Err(elevation_error("hosts file unchanged after elevated write"))
    }
}

fn site_slugs(state: &AppState) -> Vec<String> {
    list_sites(state)
        .unwrap_or_default()
        .iter()
        .map(|s| s.slug.clone())
        .collect()
}

fn get_flag(state: &AppState, key: &str) -> Result<bool, String> {
    let db = state.db.lock().map_err(|e| e.to_string())?;
    Ok(db.get_setting(key)?.as_deref() == Some("true"))
}

fn set_flag(state: &AppState, key: &str, on: bool) -> Result<(), String> {
    let db = state.db.lock().map_err(|e| e.to_string())?;
    db.set_setting(key, if on { "true" } else { "false" })
}

fn set_last_error(state: &AppState, err: Option<&str>) {
    if let Ok(db) = state.db.lock() {
        let _ = db.set_setting(KEY_LAST_ERROR, err.unwrap_or(""));
    }
}

fn list_sites(state: &AppState) -> Result<Vec<Site>, String> {
    let db = state.db.lock().map_err(|e| e.to_string())?;
    db.list_sites()
}

/// (domains_enabled, ca_trusted) — used by site creation to pick the
/// WordPress install URL. Never fails; defaults to (false, false).
pub fn enabled_and_trusted(state: &AppState) -> (bool, bool) {
    let Ok(db) = state.db.lock() else {
        return (false, false);
    };
    let enabled = db.get_setting(KEY_ENABLED).ok().flatten().as_deref() == Some("true");
    let trusted = db
        .get_setting(KEY_CA_TRUSTED)
        .ok()
        .flatten()
        .as_deref()
        == Some("true");
    (enabled, trusted)
}

pub async fn status(state: &AppState) -> Result<RouterStatus, String> {
    let (enabled, ca_trusted, last_error) = {
        let db = state.db.lock().map_err(|e| e.to_string())?;
        (
            db.get_setting(KEY_ENABLED)?.as_deref() == Some("true"),
            db.get_setting(KEY_CA_TRUSTED)?.as_deref() == Some("true"),
            db.get_setting(KEY_LAST_ERROR)?.filter(|s| !s.is_empty()),
        )
    };
    let dir = router_dir(&state.data_dir);
    let running = if dir.join("docker-compose.yml").exists() {
        match docker::compose_ps(&dir).await {
            Ok(containers) => containers
                .iter()
                .any(|c| c.service == "caddy" && c.state == "running"),
            Err(_) => false,
        }
    } else {
        false
    };
    Ok(RouterStatus {
        enabled,
        running,
        ca_trusted,
        error: last_error,
    })
}

/// Best-effort rewrite of `home`/`siteurl` for every running site.
/// Returns messages for the sites that failed (never fails the caller).
async fn rewrite_site_urls(state: &AppState, to_domains: bool) -> Vec<String> {
    let ca_trusted = get_flag(state, KEY_CA_TRUSTED).unwrap_or(false);
    let sites = list_sites(state).unwrap_or_default();
    let mut failures = Vec::new();
    for site in sites.iter().filter(|s| s.status == "running") {
        let url = if to_domains {
            site_url(&site.slug, ca_trusted)
        } else {
            format!("http://localhost:{}", site.port)
        };
        if let Err(e) = wordpress::update_site_urls(&site.dir(), &url).await {
            failures.push(format!("{}: {e}", site.name));
        }
    }
    failures
}

pub async fn set_enabled(state: &AppState, enabled: bool) -> Result<RouterStatus, String> {
    if enabled {
        let sites = list_sites(state)?;
        let dir = write_files(&state.data_dir, &sites)?;
        // Hosts entries first: if the user declines elevation, nothing else
        // changes and the flag stays off.
        if let Err(e) = sync_hosts(&site_slugs(state)).await {
            set_last_error(state, Some(&e));
            let mut st = status(state).await?;
            st.error = Some(e);
            return Ok(st);
        }
        if let Err(e) = docker::compose_up(&dir).await {
            let msg = port_conflict_hint(&e);
            // Roll back the hosts entries we just added (best-effort; this
            // may prompt for elevation again).
            let _ = sync_hosts(&[]).await;
            set_last_error(state, Some(&msg));
            let mut st = status(state).await?;
            st.error = Some(msg);
            return Ok(st);
        }
        set_flag(state, KEY_ENABLED, true)?;
        set_last_error(state, None);
        // Routes for all sites are already in the Caddyfile; make sure Caddy
        // picked the file up (compose up mounts it, but reload is harmless).
        let _ = reload(&dir).await;
        // Point running sites at their domain (best-effort).
        let failures = rewrite_site_urls(state, true).await;
        let mut st = status(state).await?;
        if !failures.is_empty() {
            st.error = Some(format!(
                "Router is running, but the WordPress URL rewrite failed for: {}",
                failures.join("; ")
            ));
        }
        Ok(st)
    } else {
        let dir = router_dir(&state.data_dir);
        if dir.join("docker-compose.yml").exists() {
            // Keep the caddy-data volume: the local CA survives re-enables.
            let _ = docker::compose_down(&dir, false).await;
        }
        set_flag(state, KEY_ENABLED, false)?;
        set_last_error(state, None);
        // Remove the managed hosts block. If elevation fails here we still
        // disable the router — stale entries just harmlessly loopback.
        let mut warning: Option<String> = None;
        if let Err(e) = sync_hosts(&[]).await {
            warning = Some(format!(
                "Local domains are off, but the hosts entries could not be removed: {e}"
            ));
        }
        // Revert running sites to localhost:<port> (best-effort).
        let failures = rewrite_site_urls(state, false).await;
        let mut st = status(state).await?;
        if !failures.is_empty() {
            warning = Some(match warning {
                Some(w) => format!(
                    "{w}\nAlso, the WordPress URL revert failed for: {}",
                    failures.join("; ")
                ),
                None => format!(
                    "Router stopped, but the WordPress URL revert failed for: {}",
                    failures.join("; ")
                ),
            });
        }
        if warning.is_some() {
            set_last_error(state, warning.as_deref());
            st.error = warning;
        }
        Ok(st)
    }
}

/// Regenerate the Caddyfile and reload Caddy after site start/stop (no hosts
/// changes — the slug set is unchanged). No-op when domains are disabled.
pub async fn refresh_routes(state: &AppState) {
    if !get_flag(state, KEY_ENABLED).unwrap_or(false) {
        return;
    }
    let Ok(sites) = list_sites(state) else { return };
    let Ok(dir) = write_files(&state.data_dir, &sites) else { return };
    let _ = reload(&dir).await;
}

/// Reconcile the managed hosts block after site create/delete (the slug set
/// changed). Elevated; best-effort — failures are recorded as the router's
/// last error rather than failing the site operation.
pub async fn refresh_hosts(state: &AppState) {
    if !get_flag(state, KEY_ENABLED).unwrap_or(false) {
        return;
    }
    if let Err(e) = sync_hosts(&site_slugs(state)).await {
        set_last_error(state, Some(&e));
    }
}

/// Extract Caddy's local-CA root cert from the container and install it into
/// the current user's OS trust store. Windows/macOS need no admin; Linux is
/// best-effort via sudo.
pub async fn trust_ca(state: &AppState) -> Result<RouterStatus, String> {
    let dir = router_dir(&state.data_dir);
    let cert_path = dir.join("caddy-root.crt");
    docker::compose_cp(&dir, "caddy", CA_CERT_CONTAINER_PATH, &cert_path)
        .await
        .map_err(|e| {
            format!(
                "Could not read the router's CA certificate (is the router running? \
                 Visit a site over https:// once so Caddy creates its local CA): {e}"
            )
        })?;
    install_ca_cert(&cert_path).await?;
    set_flag(state, KEY_CA_TRUSTED, true)?;
    status(state).await
}

async fn install_ca_cert(cert: &Path) -> Result<(), String> {
    let cert_arg = cert.to_string_lossy().to_string();
    #[cfg(target_os = "windows")]
    let (program, args): (&str, Vec<String>) = (
        "certutil",
        vec!["-user".into(), "-addstore".into(), "Root".into(), cert_arg],
    );
    #[cfg(target_os = "macos")]
    let (program, args): (&str, Vec<String>) = {
        let keychain = dirs::home_dir()
            .unwrap_or_default()
            .join("Library/Keychains/login.keychain-db")
            .to_string_lossy()
            .to_string();
        (
            "security",
            vec!["add-trusted-cert".into(), "-k".into(), keychain, cert_arg],
        )
    };
    #[cfg(all(unix, not(target_os = "macos")))]
    let (program, args): (&str, Vec<String>) = (
        "sh",
        vec![
            "-c".into(),
            format!(
                "sudo cp '{}' /usr/local/share/ca-certificates/localkit-root.crt && sudo update-ca-certificates",
                cert_arg.replace('\'', "'\\''")
            ),
        ],
    );
    let output = docker::no_window(tokio::process::Command::new(program).args(&args))
        .output()
        .await
        .map_err(|e| format!("failed to run {program}: {e}"))?;
    if output.status.success() {
        Ok(())
    } else {
        let stderr = String::from_utf8_lossy(&output.stderr);
        let stdout = String::from_utf8_lossy(&output.stdout);
        let detail = if stderr.trim().is_empty() {
            stdout.trim()
        } else {
            stderr.trim()
        };
        Err(format!(
            "Failed to trust the LocalKit CA ({program}): {}",
            detail.chars().take(300).collect::<String>()
        ))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn slugs(names: &[&str]) -> Vec<String> {
        names.iter().map(|s| s.to_string()).collect()
    }

    const SAMPLE: &str = "# Copyright (c) Microsoft Corp.\r\n\
                          \r\n\
                          127.0.0.1  localhost\r\n\
                          ::1        localhost\r\n";

    #[test]
    fn insert_block_preserves_existing_content() {
        let out = update_hosts_content(SAMPLE, &slugs(&["pixel-bakery", "acme"]));
        assert!(out.starts_with("# Copyright (c) Microsoft Corp."));
        assert!(out.contains("127.0.0.1  localhost"));
        assert!(out.contains("# BEGIN LOCALKIT"));
        assert!(out.contains("127.0.0.1  pixel-bakery.test"));
        assert!(out.contains("127.0.0.1  acme.test"));
        assert!(out.contains("# END LOCALKIT"));
        assert!(out.contains("\r\n"), "CRLF line endings preserved");
    }

    #[test]
    fn insert_is_idempotent() {
        let once = update_hosts_content(SAMPLE, &slugs(&["pixel-bakery"]));
        let twice = update_hosts_content(&once, &slugs(&["pixel-bakery"]));
        assert_eq!(once, twice);
        assert_eq!(twice.matches(HOSTS_BEGIN).count(), 1);
    }

    #[test]
    fn block_is_replaced_not_duplicated() {
        let first = update_hosts_content(SAMPLE, &slugs(&["a", "b"]));
        let second = update_hosts_content(&first, &slugs(&["b", "c"]));
        assert!(!second.contains("a.test"));
        assert!(second.contains("b.test"));
        assert!(second.contains("c.test"));
        assert_eq!(second.matches(HOSTS_BEGIN).count(), 1);
    }

    #[test]
    fn empty_slug_list_removes_block() {
        let with = update_hosts_content(SAMPLE, &slugs(&["pixel-bakery"]));
        let without = update_hosts_content(&with, &[]);
        assert!(!without.contains("LOCALKIT"));
        assert!(!without.contains("pixel-bakery.test"));
        assert_eq!(without, SAMPLE, "removal restores the original file");
    }

    #[test]
    fn remove_without_block_is_byte_identical() {
        assert_eq!(update_hosts_content(SAMPLE, &[]), SAMPLE);
        assert_eq!(update_hosts_content("", &[]), "");
    }

    #[test]
    fn lf_only_file_stays_lf() {
        let lf = "127.0.0.1  localhost\n::1  localhost\n";
        let out = update_hosts_content(lf, &slugs(&["x"]));
        assert!(!out.contains("\r\n"));
        assert!(out.contains("127.0.0.1  x.test"));
    }

    #[test]
    fn staged_content_round_trips_through_temp_file() {
        // Mirrors what sync_hosts stages for the elevated writer.
        let desired = update_hosts_content(SAMPLE, &slugs(&["one", "two"]));
        let tmp = std::env::temp_dir().join("localkit-hosts-test-roundtrip.txt");
        std::fs::write(&tmp, &desired).unwrap();
        let read_back = std::fs::read_to_string(&tmp).unwrap();
        let _ = std::fs::remove_file(&tmp);
        assert_eq!(read_back, desired);
        // Applying the same slugs again is a no-op (desired == current).
        assert_eq!(update_hosts_content(&read_back, &slugs(&["one", "two"])), read_back);
    }
}
