//! WordPress management via wp-cli.
//!
//! The stock `wordpress` image does NOT bundle wp-cli, so each site compose
//! file includes a profile-gated `wpcli` service (the official
//! `wordpress:cli` image) and we run commands with
//! `docker compose run --rm -T wpcli wp <args...>`.

use serde::{Deserialize, Serialize};
use std::path::Path;
use tauri::AppHandle;

use crate::docker;
use crate::site::{self, Site};

#[derive(Debug, Clone, Serialize)]
pub struct PluginInfo {
    pub name: String,
    pub status: String,
    pub version: String,
}

#[derive(Debug, Clone, Serialize)]
pub struct WpInfo {
    pub core_version: String,
    pub plugins: Vec<PluginInfo>,
}

#[derive(Deserialize)]
struct RawPlugin {
    name: String,
    status: String,
    #[serde(default)]
    version: String,
}

/// A WordPress user, for the WP Admin login picker.
#[derive(Debug, Clone, Serialize)]
pub struct WpUser {
    pub id: u64,
    pub login: String,
    pub name: String,
    pub roles: String,
}

#[derive(Deserialize)]
struct RawUser {
    #[serde(rename = "ID")]
    id: u64,
    user_login: String,
    #[serde(default)]
    display_name: String,
    #[serde(default)]
    roles: String,
}

// ---------------------------------------------------------------------------
// One-click WP Admin login (one-time token + must-use plugin)
// ---------------------------------------------------------------------------

/// Must-use plugin dropped into `wp-content/mu-plugins/` (bind-mounted into
/// the container, so a plain fs write works stopped or running). It consumes
/// one-time login tokens on `wp-login.php?localkit-login=<hex>&uid=<id>`:
/// constant-time compare, ~2-minute TTL, single use, then sets the auth
/// cookie and redirects to wp-admin. Any failure falls through to the normal
/// login form with no error detail.
pub const LOGIN_PLUGIN: &str = r#"<?php
/**
 * Plugin Name: LocalKit One-Click Login
 * Description: Consumes the one-time login tokens generated by LocalKit's "WP Admin" button. Safe to delete.
 *
 * @package localkit
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

add_action(
	'init',
	function () {
		global $pagenow;
		if ( 'wp-login.php' !== $pagenow || empty( $_GET['localkit-login'] ) ) {
			return;
		}

		$token  = sanitize_text_field( wp_unslash( $_GET['localkit-login'] ) );
		$stored = get_option( 'localkit_login_token' );
		$expiry = (int) get_option( 'localkit_login_exp' );

		// One-time use: always consume the token, valid or not.
		delete_option( 'localkit_login_token' );
		delete_option( 'localkit_login_exp' );

		if ( ! is_string( $stored ) || ! hash_equals( $stored, $token ) || time() > $expiry ) {
			return; // Fall through to the normal login form.
		}

		$user_id = isset( $_GET['uid'] ) ? absint( $_GET['uid'] ) : 0;
		$user    = get_user_by( 'id', $user_id );
		if ( ! $user ) {
			return;
		}

		wp_set_current_user( $user->ID, $user->user_login );
		wp_set_auth_cookie( $user->ID );
		wp_safe_redirect( admin_url() );
		exit;
	}
);
"#;

/// Seconds a login token stays valid.
const LOGIN_TOKEN_TTL: i64 = 120;

/// Write the MU login plugin idempotently (skip when the file is already
/// identical, so upgrades can replace it later).
pub fn ensure_login_plugin(dir: &Path) -> Result<(), String> {
    let mu_dir = dir.join("wp-content").join("mu-plugins");
    let path = mu_dir.join("localkit-login.php");
    if std::fs::read_to_string(&path).is_ok_and(|existing| existing == LOGIN_PLUGIN) {
        return Ok(());
    }
    std::fs::create_dir_all(&mu_dir).map_err(|e| format!("failed to create mu-plugins dir: {e}"))?;
    std::fs::write(&path, LOGIN_PLUGIN).map_err(|e| format!("failed to write login plugin: {e}"))
}

/// List the site's WordPress users (for the WP Admin login picker).
pub async fn users(dir: &Path) -> Result<Vec<WpUser>, String> {
    let json = wp(
        dir,
        &[
            "user",
            "list",
            "--fields=ID,user_login,display_name,roles",
            "--format=json",
        ],
    )
    .await?;
    let raw: Vec<RawUser> =
        serde_json::from_str(&json).map_err(|e| format!("failed to parse user list: {e}"))?;
    Ok(raw
        .into_iter()
        .map(|u| WpUser {
            id: u.id,
            login: u.user_login,
            name: u.display_name,
            roles: u.roles,
        })
        .collect())
}

/// Build a one-time login URL for `wp-login.php`. `user` is an id, login, or
/// email; `None` logs in as the site's default admin (falling back to the
/// first administrator — the stored `admin_user` may not exist after a DB
/// pull). The token is never logged: callers must not echo the full URL into
/// events or history.
pub async fn login_url(
    dir: &Path,
    site: &Site,
    user: Option<&str>,
    base_url: &str,
) -> Result<String, String> {
    // Lazy install for sites created before this feature existed.
    ensure_login_plugin(dir)?;
    let uid = match user {
        Some(u) => resolve_user_id(dir, u).await?,
        None => default_user_id(dir, site).await?,
    };
    let token = login_token();
    let expiry = (chrono::Utc::now().timestamp() + LOGIN_TOKEN_TTL).to_string();
    wp(dir, &["option", "update", "localkit_login_token", &token, "--autoload=no"]).await?;
    wp(dir, &["option", "update", "localkit_login_exp", &expiry, "--autoload=no"]).await?;
    Ok(format!("{base_url}/wp-login.php?localkit-login={token}&uid={uid}"))
}

/// Resolve an id / login / email to a user id.
async fn resolve_user_id(dir: &Path, user: &str) -> Result<u64, String> {
    if let Ok(id) = user.parse::<u64>() {
        return Ok(id);
    }
    let out = wp(dir, &["user", "get", user, "--field=ID"])
        .await
        .map_err(|e| format!("no WordPress user matching `{user}`: {e}"))?;
    out.trim()
        .parse()
        .map_err(|_| format!("unexpected wp-cli output resolving user `{user}`"))
}

/// The site's `admin_user`, or the first administrator when that login no
/// longer exists locally (e.g. after a pull DB overwrote users).
async fn default_user_id(dir: &Path, site: &Site) -> Result<u64, String> {
    if let Ok(out) = wp(dir, &["user", "get", &site.admin_user, "--field=ID"]).await {
        if let Ok(id) = out.trim().parse::<u64>() {
            return Ok(id);
        }
    }
    let out = wp(dir, &["user", "list", "--role=administrator", "--field=ID"]).await?;
    out.lines()
        .next()
        .and_then(|l| l.trim().parse().ok())
        .ok_or_else(|| "no administrator account found in this site's database".into())
}

/// 32 random bytes, hex-encoded.
fn login_token() -> String {
    use rand::Rng;
    let bytes: [u8; 32] = rand::thread_rng().gen();
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

/// Run wp-cli inside the site project. The `wordpress:cli` image entrypoint
/// expects `wp` as the first argument (its `wp` CMD is replaced by run args).
async fn wp(dir: &Path, args: &[&str]) -> Result<String, String> {
    let mut full: Vec<&str> = Vec::with_capacity(args.len() + 1);
    full.push("wp");
    full.extend_from_slice(args);
    docker::compose_run(dir, "wpcli", &full).await
}

/// Auto-install WordPress with generated admin credentials.
/// `url` is the public URL the site will be reached at (localhost:<port> or,
/// when local domains are enabled, http(s)://<slug>.test).
/// Retries while the containers/DB finish their first boot; each attempt
/// re-emits the `install` stage so the UI never looks hung.
pub async fn install(
    dir: &Path,
    site: &Site,
    admin_pass: &str,
    url: &str,
    app: Option<&AppHandle>,
) -> Result<(), String> {
    let url_arg = format!("--url={url}");
    let title_arg = format!("--title={}", site.name);
    let user_arg = format!("--admin_user={}", site.admin_user);
    let pass_arg = format!("--admin_password={admin_pass}");
    let email_arg = format!("--admin_email=admin@{}.local", site.slug);
    let install_args = [
        "core",
        "install",
        &url_arg,
        &title_arg,
        &user_arg,
        &pass_arg,
        &email_arg,
        "--skip-email",
    ];

    const ATTEMPTS: u32 = 12;
    let mut last_err = String::new();
    for attempt in 1..=ATTEMPTS {
        site::emit(
            app,
            &site.id,
            "install",
            &if attempt == 1 {
                "Installing WordPress...".to_string()
            } else {
                format!("Installing WordPress... (attempt {attempt}/{ATTEMPTS}, waiting for database)")
            },
        );
        // Already installed? Nothing to do.
        if wp(dir, &["core", "is-installed"]).await.is_ok() {
            return Ok(());
        }
        match wp(dir, &install_args).await {
            Ok(_) => return Ok(()),
            Err(e) => {
                last_err = e;
                tokio::time::sleep(std::time::Duration::from_secs(5)).await;
            }
        }
    }
    Err(format!("WordPress install failed: {last_err}"))
}

/// Whether WordPress core is already installed (plan 23 resume: don't re-run
/// `core install` on a site whose database already holds one).
pub async fn is_installed(dir: &Path) -> bool {
    wp(dir, &["core", "is-installed"]).await.is_ok()
}

/// Wait until wp-cli can see the site's `wp-config.php`.
///
/// `site::wait_for_port` is not a sufficient readiness signal on its own:
/// Docker publishes the host port as soon as the container is *created*, so a
/// TCP connect succeeds while the wordpress image's entrypoint is still
/// unpacking core and writing wp-config.php. `install` happens to survive this
/// because it retries for a minute; anything else that shells into wp-cli
/// straight after `compose up` has to wait explicitly, or it fails with a bare
/// "'wp-config.php' not found".
pub async fn wait_for_config(dir: &Path, attempts: u32) -> Result<(), String> {
    let mut last = String::new();
    for attempt in 1..=attempts {
        match wp(dir, &["config", "path"]).await {
            Ok(_) => return Ok(()),
            Err(e) => last = e,
        }
        if attempt < attempts {
            tokio::time::sleep(std::time::Duration::from_secs(5)).await;
        }
    }
    Err(format!("WordPress did not finish initializing: {last}"))
}

/// Read-only info for the UI: core version + plugin list.
pub async fn info(dir: &Path) -> Result<WpInfo, String> {
    let core_version = wp(dir, &["core", "version"]).await?.trim().to_string();
    let plugins_json = wp(dir, &["plugin", "list", "--format=json"]).await?;
    let raw: Vec<RawPlugin> = serde_json::from_str(&plugins_json)
        .map_err(|e| format!("failed to parse plugin list: {e}"))?;
    Ok(WpInfo {
        core_version,
        plugins: raw
            .into_iter()
            .map(|p| PluginInfo {
                name: p.name,
                status: p.status,
                version: p.version,
            })
            .collect(),
    })
}

/// Export the site database to a SQL file on the host.
pub async fn export_db(dir: &Path, dest: &Path) -> Result<(), String> {
    let sql = wp(dir, &["db", "export", "-"]).await?;
    std::fs::write(dest, sql).map_err(|e| format!("failed to write database dump: {e}"))
}

/// Import a SQL dump through wp-cli's stdin (`wp db import -`).
pub async fn import_db(dir: &Path, sql: &[u8]) -> Result<(), String> {
    docker::compose_run_stdin(dir, "wpcli", &["wp", "db", "import", "-"], sql)
        .await
        .map(|_| ())
}

/// Import a gzipped dump straight off disk, decompressing into the pipe.
///
/// The streaming counterpart of `import_db`, used by the pull/import flows so
/// a remote database never has to exist decompressed in memory (plan 19).
pub async fn import_db_from_gz(dir: &Path, gz_path: &Path) -> Result<(), String> {
    let file = std::fs::File::open(gz_path)
        .map_err(|e| format!("failed to open the downloaded dump: {e}"))?;
    let mut reader = flate2::read::GzDecoder::new(std::io::BufReader::new(file));
    docker::compose_run_reader(dir, "wpcli", &["wp", "db", "import", "-"], &mut reader)
        .await
        .map(|_| ())
}

/// Serialization-safe URL rewrite across all tables.
pub async fn search_replace(dir: &Path, from: &str, to: &str) -> Result<(), String> {
    wp(dir, &["search-replace", from, to, "--all-tables"])
        .await
        .map(|_| ())
}

/// Point home/siteurl at the site's local URL.
pub async fn update_site_urls(dir: &Path, url: &str) -> Result<(), String> {
    wp(dir, &["option", "update", "home", url]).await?;
    wp(dir, &["option", "update", "siteurl", url]).await?;
    Ok(())
}
