//! WordPress management via wp-cli.
//!
//! The stock `wordpress` image does NOT bundle wp-cli, so each site compose
//! file includes a profile-gated `wpcli` service (the official
//! `wordpress:cli` image) and we run commands with
//! `docker compose run --rm -T wpcli wp <args...>`.

use serde::{Deserialize, Serialize};
use std::path::{Path, PathBuf};
use tauri::AppHandle;

use crate::docker;
use crate::site::{self, Site};

#[derive(Debug, Clone, Serialize)]
pub struct PluginInfo {
    pub name: String,
    pub status: String,
    pub version: String,
}

#[derive(Debug, Clone, Serialize)]
pub struct WpInfo {
    pub core_version: String,
    pub plugins: Vec<PluginInfo>,
}

#[derive(Deserialize)]
struct RawPlugin {
    name: String,
    status: String,
    #[serde(default)]
    version: String,
}

/// A WordPress user, for the WP Admin login picker.
#[derive(Debug, Clone, Serialize)]
pub struct WpUser {
    pub id: u64,
    pub login: String,
    pub name: String,
    pub roles: String,
}

#[derive(Deserialize)]
struct RawUser {
    #[serde(rename = "ID")]
    id: u64,
    user_login: String,
    #[serde(default)]
    display_name: String,
    #[serde(default)]
    roles: String,
}

// ---------------------------------------------------------------------------
// One-click WP Admin login (one-time token + must-use plugin)
// ---------------------------------------------------------------------------

/// Must-use plugin dropped into `wp-content/mu-plugins/` (bind-mounted into
/// the container, so a plain fs write works stopped or running). It consumes
/// one-time login tokens on `wp-login.php?localkit-login=<hex>&uid=<id>`:
/// constant-time compare, ~2-minute TTL, single use, then sets the auth
/// cookie and redirects to wp-admin. Any failure falls through to the normal
/// login form with no error detail.
pub const LOGIN_PLUGIN: &str = r#"<?php
/**
 * Plugin Name: LocalKit One-Click Login
 * Description: Consumes the one-time login tokens generated by LocalKit's "WP Admin" button. Safe to delete.
 *
 * @package localkit
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

add_action(
	'init',
	function () {
		global $pagenow;
		if ( 'wp-login.php' !== $pagenow || empty( $_GET['localkit-login'] ) ) {
			return;
		}

		$token  = sanitize_text_field( wp_unslash( $_GET['localkit-login'] ) );
		$stored = get_option( 'localkit_login_token' );
		$expiry = (int) get_option( 'localkit_login_exp' );

		// One-time use: always consume the token, valid or not.
		delete_option( 'localkit_login_token' );
		delete_option( 'localkit_login_exp' );

		if ( ! is_string( $stored ) || ! hash_equals( $stored, $token ) || time() > $expiry ) {
			return; // Fall through to the normal login form.
		}

		$user_id = isset( $_GET['uid'] ) ? absint( $_GET['uid'] ) : 0;
		$user    = get_user_by( 'id', $user_id );
		if ( ! $user ) {
			return;
		}

		wp_set_current_user( $user->ID, $user->user_login );
		wp_set_auth_cookie( $user->ID );
		wp_safe_redirect( admin_url() );
		exit;
	}
);
"#;

/// Seconds a login token stays valid.
const LOGIN_TOKEN_TTL: i64 = 120;

/// Write the MU login plugin idempotently (skip when the file is already
/// identical, so upgrades can replace it later).
pub fn ensure_login_plugin(dir: &Path) -> Result<(), String> {
    let mu_dir = dir.join("wp-content").join("mu-plugins");
    let path = mu_dir.join("localkit-login.php");
    if std::fs::read_to_string(&path).is_ok_and(|existing| existing == LOGIN_PLUGIN) {
        return Ok(());
    }
    std::fs::create_dir_all(&mu_dir).map_err(|e| format!("failed to create mu-plugins dir: {e}"))?;
    std::fs::write(&path, LOGIN_PLUGIN).map_err(|e| format!("failed to write login plugin: {e}"))
}

/// List the site's WordPress users (for the WP Admin login picker).
pub async fn users(dir: &Path) -> Result<Vec<WpUser>, String> {
    let json = wp(
        dir,
        &[
            "user",
            "list",
            "--fields=ID,user_login,display_name,roles",
            "--format=json",
        ],
    )
    .await?;
    let raw: Vec<RawUser> =
        serde_json::from_str(&json).map_err(|e| format!("failed to parse user list: {e}"))?;
    Ok(raw
        .into_iter()
        .map(|u| WpUser {
            id: u.id,
            login: u.user_login,
            name: u.display_name,
            roles: u.roles,
        })
        .collect())
}

/// Build a one-time login URL for `wp-login.php`. `user` is an id, login, or
/// email; `None` logs in as the site's default admin (falling back to the
/// first administrator — the stored `admin_user` may not exist after a DB
/// pull). The token is never logged: callers must not echo the full URL into
/// events or history.
pub async fn login_url(
    dir: &Path,
    site: &Site,
    user: Option<&str>,
    base_url: &str,
) -> Result<String, String> {
    // Lazy install for sites created before this feature existed.
    ensure_login_plugin(dir)?;
    let uid = match user {
        Some(u) => resolve_user_id(dir, u).await?,
        None => default_user_id(dir, site).await?,
    };
    let token = login_token();
    let expiry = (chrono::Utc::now().timestamp() + LOGIN_TOKEN_TTL).to_string();
    wp(dir, &["option", "update", "localkit_login_token", &token, "--autoload=no"]).await?;
    wp(dir, &["option", "update", "localkit_login_exp", &expiry, "--autoload=no"]).await?;
    Ok(format!("{base_url}/wp-login.php?localkit-login={token}&uid={uid}"))
}

/// Resolve an id / login / email to a user id.
async fn resolve_user_id(dir: &Path, user: &str) -> Result<u64, String> {
    if let Ok(id) = user.parse::<u64>() {
        return Ok(id);
    }
    let out = wp(dir, &["user", "get", user, "--field=ID"])
        .await
        .map_err(|e| format!("no WordPress user matching `{user}`: {e}"))?;
    out.trim()
        .parse()
        .map_err(|_| format!("unexpected wp-cli output resolving user `{user}`"))
}

/// The site's `admin_user`, or the first administrator when that login no
/// longer exists locally (e.g. after a pull DB overwrote users).
async fn default_user_id(dir: &Path, site: &Site) -> Result<u64, String> {
    if let Ok(out) = wp(dir, &["user", "get", &site.admin_user, "--field=ID"]).await {
        if let Ok(id) = out.trim().parse::<u64>() {
            return Ok(id);
        }
    }
    let out = wp(dir, &["user", "list", "--role=administrator", "--field=ID"]).await?;
    out.lines()
        .next()
        .and_then(|l| l.trim().parse().ok())
        .ok_or_else(|| "no administrator account found in this site's database".into())
}

/// 32 random bytes, hex-encoded.
fn login_token() -> String {
    use rand::Rng;
    let bytes: [u8; 32] = rand::thread_rng().gen();
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

/// Run wp-cli inside the site project. The `wordpress:cli` image entrypoint
/// expects `wp` as the first argument (its `wp` CMD is replaced by run args).
async fn wp(dir: &Path, args: &[&str]) -> Result<String, String> {
    let mut full: Vec<&str> = Vec::with_capacity(args.len() + 1);
    full.push("wp");
    full.extend_from_slice(args);
    docker::compose_run(dir, "wpcli", &full).await
}

/// Run wp-cli as root, for commands that write `wp-config.php` (root-owned in
/// the wp-data volume — see `docker::compose_run_root`). `--allow-root` is
/// appended because wp-cli refuses to run as root without it.
async fn wp_root(dir: &Path, args: &[&str]) -> Result<String, String> {
    let mut full: Vec<&str> = Vec::with_capacity(args.len() + 2);
    full.push("wp");
    full.extend_from_slice(args);
    full.push("--allow-root");
    docker::compose_run_root(dir, "wpcli", &full).await
}

/// Auto-install WordPress with generated admin credentials.
/// `url` is the public URL the site will be reached at (localhost:<port> or,
/// when local domains are enabled, http(s)://<slug>.test).
/// Retries while the containers/DB finish their first boot; each attempt
/// re-emits the `install` stage so the UI never looks hung.
pub async fn install(
    dir: &Path,
    site: &Site,
    admin_pass: &str,
    url: &str,
    app: Option<&AppHandle>,
) -> Result<(), String> {
    let url_arg = format!("--url={url}");
    let title_arg = format!("--title={}", site.name);
    let user_arg = format!("--admin_user={}", site.admin_user);
    let pass_arg = format!("--admin_password={admin_pass}");
    let email_arg = format!("--admin_email=admin@{}.local", site.slug);
    let install_args = [
        "core",
        "install",
        &url_arg,
        &title_arg,
        &user_arg,
        &pass_arg,
        &email_arg,
        "--skip-email",
    ];

    const ATTEMPTS: u32 = 12;
    let mut last_err = String::new();
    for attempt in 1..=ATTEMPTS {
        site::emit(
            app,
            &site.id,
            "install",
            &if attempt == 1 {
                "Installing WordPress...".to_string()
            } else {
                format!("Installing WordPress... (attempt {attempt}/{ATTEMPTS}, waiting for database)")
            },
        );
        // Already installed? Nothing to do.
        if wp(dir, &["core", "is-installed"]).await.is_ok() {
            return Ok(());
        }
        match wp(dir, &install_args).await {
            Ok(_) => return Ok(()),
            Err(e) => {
                last_err = e;
                tokio::time::sleep(std::time::Duration::from_secs(5)).await;
            }
        }
    }
    Err(format!("WordPress install failed: {last_err}"))
}

/// Whether WordPress core is already installed (plan 23 resume: don't re-run
/// `core install` on a site whose database already holds one).
pub async fn is_installed(dir: &Path) -> bool {
    wp(dir, &["core", "is-installed"]).await.is_ok()
}

/// Wait until wp-cli can see the site's `wp-config.php`.
///
/// `site::wait_for_port` is not a sufficient readiness signal on its own:
/// Docker publishes the host port as soon as the container is *created*, so a
/// TCP connect succeeds while the wordpress image's entrypoint is still
/// unpacking core and writing wp-config.php. `install` happens to survive this
/// because it retries for a minute; anything else that shells into wp-cli
/// straight after `compose up` has to wait explicitly, or it fails with a bare
/// "'wp-config.php' not found".
pub async fn wait_for_config(dir: &Path, attempts: u32) -> Result<(), String> {
    let mut last = String::new();
    for attempt in 1..=attempts {
        match wp(dir, &["config", "path"]).await {
            Ok(_) => return Ok(()),
            Err(e) => last = e,
        }
        if attempt < attempts {
            tokio::time::sleep(std::time::Duration::from_secs(5)).await;
        }
    }
    Err(format!("WordPress did not finish initializing: {last}"))
}

/// Read-only info for the UI: core version + plugin list.
pub async fn info(dir: &Path) -> Result<WpInfo, String> {
    let core_version = wp(dir, &["core", "version"]).await?.trim().to_string();
    let plugins_json = wp(dir, &["plugin", "list", "--format=json"]).await?;
    let raw: Vec<RawPlugin> = serde_json::from_str(&plugins_json)
        .map_err(|e| format!("failed to parse plugin list: {e}"))?;
    Ok(WpInfo {
        core_version,
        plugins: raw
            .into_iter()
            .map(|p| PluginInfo {
                name: p.name,
                status: p.status,
                version: p.version,
            })
            .collect(),
    })
}

/// Export the site database to a SQL file on the host.
pub async fn export_db(dir: &Path, dest: &Path) -> Result<(), String> {
    let sql = wp(dir, &["db", "export", "-"]).await?;
    std::fs::write(dest, sql).map_err(|e| format!("failed to write database dump: {e}"))
}

/// Import a SQL dump through wp-cli's stdin (`wp db import -`).
pub async fn import_db(dir: &Path, sql: &[u8]) -> Result<(), String> {
    docker::compose_run_stdin(dir, "wpcli", &["wp", "db", "import", "-"], sql)
        .await
        .map(|_| ())
}

/// Import a gzipped dump straight off disk, decompressing into the pipe.
///
/// The streaming counterpart of `import_db`, used by the pull/import flows so
/// a remote database never has to exist decompressed in memory (plan 19).
pub async fn import_db_from_gz(dir: &Path, gz_path: &Path) -> Result<(), String> {
    let file = std::fs::File::open(gz_path)
        .map_err(|e| format!("failed to open the downloaded dump: {e}"))?;
    let mut reader = flate2::read::GzDecoder::new(std::io::BufReader::new(file));
    docker::compose_run_reader(dir, "wpcli", &["wp", "db", "import", "-"], &mut reader)
        .await
        .map(|_| ())
}

/// Serialization-safe URL rewrite across all tables.
pub async fn search_replace(dir: &Path, from: &str, to: &str) -> Result<(), String> {
    wp(dir, &["search-replace", from, to, "--all-tables"])
        .await
        .map(|_| ())
}

/// One `table.column` line of a search-replace report.
#[derive(Debug, Clone, Serialize)]
pub struct SearchReplaceChange {
    pub table: String,
    pub column: String,
    pub count: u64,
}

/// The outcome of a search-replace: total replacements and the per-column
/// breakdown wp-cli reports (only changed columns, `--report-changed-only`).
#[derive(Debug, Clone, Serialize)]
pub struct SearchReplaceResult {
    pub dry_run: bool,
    pub total: u64,
    pub changes: Vec<SearchReplaceChange>,
}

/// Run a serialization-safe search-replace and report what changed.
///
/// `wp search-replace <from> <to> --all-tables --precise --report-changed-only
/// [--dry-run]` — never a raw SQL `REPLACE`, so PHP-serialized values (widget
/// data, options) survive. `--dry-run` counts without writing, which is what the
/// UI runs first so the user sees the cost before committing. The table output
/// is parsed into a structured result; the total is the sum of the per-column
/// counts.
pub async fn search_replace_report(
    dir: &Path,
    from: &str,
    to: &str,
    dry_run: bool,
) -> Result<SearchReplaceResult, String> {
    let mut args = vec![
        "search-replace",
        from,
        to,
        "--all-tables",
        "--precise",
        "--report-changed-only",
    ];
    if dry_run {
        args.push("--dry-run");
    }
    let output = wp(dir, &args).await?;
    let (total, changes) = parse_search_replace_table(&output);
    Ok(SearchReplaceResult { dry_run, total, changes })
}

/// Parse wp-cli's search-replace report into (total, per-column rows).
///
/// The columns are `Table Column Replacements Type`, and
/// `--report-changed-only` shows only rows with a non-zero count (a zero-change
/// run prints no table at all → empty stdout → 0 changes). wp-cli emits this in
/// one of two shapes depending on whether stdout is a TTY: the plain
/// tab-separated form (what LocalKit gets, since it captures a pipe) or the
/// bordered `| a | b |` grid. Both are handled. Column *positions* come from the
/// header row rather than being assumed, so a reordered/extra column still maps.
fn parse_search_replace_table(output: &str) -> (u64, Vec<SearchReplaceChange>) {
    let cells_of = |line: &str| -> Vec<String> {
        if line.contains('|') {
            // Bordered grid: `| a | b |` — drop the empty ends the outer pipes
            // produce, but keep genuinely empty inner cells.
            let mut cells: Vec<String> = line.split('|').map(|c| c.trim().to_string()).collect();
            if cells.first().is_some_and(|s| s.is_empty()) {
                cells.remove(0);
            }
            if cells.last().is_some_and(|s| s.is_empty()) {
                cells.pop();
            }
            cells
        } else {
            // Tab-separated (the non-TTY form wp-cli actually gives us).
            line.split('\t').map(|c| c.trim().to_string()).collect()
        }
    };

    let rows: Vec<Vec<String>> = output
        .lines()
        .map(str::trim)
        .filter(|l| !l.is_empty() && !l.starts_with('+') && (l.contains('|') || l.contains('\t')))
        .map(cells_of)
        .collect();

    // Locate the header and the columns we care about within it.
    let Some(header_idx) = rows
        .iter()
        .position(|r| r.iter().any(|c| c.eq_ignore_ascii_case("Replacements")))
    else {
        return (0, Vec::new());
    };
    let header = &rows[header_idx];
    let col = |name: &str| header.iter().position(|c| c.eq_ignore_ascii_case(name));
    let (table_i, column_i, count_i) = (col("Table"), col("Column"), col("Replacements"));
    let Some(count_i) = count_i else {
        return (0, Vec::new());
    };

    let mut total = 0u64;
    let mut changes = Vec::new();
    for row in &rows[header_idx + 1..] {
        let count = row.get(count_i).and_then(|c| c.parse::<u64>().ok());
        let Some(count) = count else { continue };
        total += count;
        changes.push(SearchReplaceChange {
            table: table_i.and_then(|i| row.get(i)).cloned().unwrap_or_default(),
            column: column_i.and_then(|i| row.get(i)).cloned().unwrap_or_default(),
            count,
        });
    }
    (total, changes)
}

// ---------------------------------------------------------------------------
// Debug mode + log viewer (plan 24)
// ---------------------------------------------------------------------------

/// WP_DEBUG state + the size of the debug log, for the Tools → Debug UI.
#[derive(Debug, Clone, Serialize)]
pub struct DebugStatus {
    pub enabled: bool,
    /// Bytes in `wp-content/debug.log` (0 when absent), so the UI can say
    /// "empty" without shipping the whole file just to check.
    pub log_bytes: u64,
}

/// Host path of the WordPress debug log. `WP_DEBUG_LOG = true` logs to
/// `WP_CONTENT_DIR/debug.log`, and `wp-content` is bind-mounted, so this is a
/// plain host file — read/cleared without touching the container.
fn debug_log_path(dir: &Path) -> PathBuf {
    dir.join("wp-content").join("debug.log")
}

/// Read WP_DEBUG. `wp config get WP_DEBUG` *evaluates* the constant, so a true
/// value prints `1` and a false/undefined one prints empty.
pub async fn debug_status(dir: &Path) -> Result<DebugStatus, String> {
    let value = wp(dir, &["config", "get", "WP_DEBUG"]).await.unwrap_or_default();
    let value = value.trim();
    let enabled = value == "1" || value.eq_ignore_ascii_case("true");
    let log_bytes = std::fs::metadata(debug_log_path(dir))
        .map(|m| m.len())
        .unwrap_or(0);
    Ok(DebugStatus { enabled, log_bytes })
}

/// Toggle debug mode: `WP_DEBUG` and `WP_DEBUG_LOG` follow `enabled`, while
/// `WP_DEBUG_DISPLAY` is pinned false — errors go to the log, never to the
/// screen (a visible fatal on a shared preview URL is its own footgun). Writing
/// `wp-config.php` needs the root runner (see `wp_root`).
pub async fn set_debug(dir: &Path, enabled: bool) -> Result<DebugStatus, String> {
    let raw = if enabled { "true" } else { "false" };
    wp_root(dir, &["config", "set", "WP_DEBUG", raw, "--raw"]).await?;
    wp_root(dir, &["config", "set", "WP_DEBUG_LOG", raw, "--raw"]).await?;
    wp_root(dir, &["config", "set", "WP_DEBUG_DISPLAY", "false", "--raw"]).await?;
    debug_status(dir).await
}

/// The debug log, tailed to the last ~128 KB so a runaway log never blows up
/// the IPC payload. Empty string when the file does not exist yet.
pub fn read_debug_log(dir: &Path) -> String {
    let Ok(bytes) = std::fs::read(debug_log_path(dir)) else {
        return String::new();
    };
    const MAX: usize = 128 * 1024;
    let slice = if bytes.len() > MAX {
        &bytes[bytes.len() - MAX..]
    } else {
        &bytes[..]
    };
    String::from_utf8_lossy(slice).to_string()
}

/// Truncate the debug log (kept as an empty file so PHP keeps appending to the
/// same inode). A missing log is a no-op.
pub fn clear_debug_log(dir: &Path) -> Result<(), String> {
    let path = debug_log_path(dir);
    if path.exists() {
        std::fs::write(&path, b"").map_err(|e| format!("failed to clear the debug log: {e}"))?;
    }
    Ok(())
}

/// Point home/siteurl at the site's local URL.
pub async fn update_site_urls(dir: &Path, url: &str) -> Result<(), String> {
    wp(dir, &["option", "update", "home", url]).await?;
    wp(dir, &["option", "update", "siteurl", url]).await?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    const REPORT: &str = "\
+------------+---------------+--------------+------+
| Table      | Column        | Replacements | Type |
+------------+---------------+--------------+------+
| wp_options | option_value  | 3            | PHP  |
| wp_posts   | post_content  | 12           | SQL  |
| wp_posts   | guid          | 4            | SQL  |
+------------+---------------+--------------+------+";

    #[test]
    fn parses_the_report_table_into_rows_and_a_total() {
        let (total, changes) = parse_search_replace_table(REPORT);
        assert_eq!(total, 19);
        assert_eq!(changes.len(), 3);
        assert_eq!(changes[0].table, "wp_options");
        assert_eq!(changes[0].column, "option_value");
        assert_eq!(changes[0].count, 3);
        assert_eq!(changes[1].count, 12);
        assert_eq!(changes[2].column, "guid");
    }

    /// The shape LocalKit actually gets: wp-cli drops the ASCII grid when
    /// stdout is a pipe and emits a tab-separated table instead (captured from a
    /// real `wp search-replace ... --report-changed-only --dry-run`).
    #[test]
    fn parses_the_tab_separated_form_wp_cli_actually_emits() {
        let tsv = "Table\tColumn\tReplacements\tType\n\
                   wp_options\toption_value\t2\tPHP\n\
                   wp_posts\tpost_content\t2\tPHP\n\
                   wp_posts\tguid\t4\tPHP\n\
                   wp_users\tuser_url\t1\tPHP";
        let (total, changes) = parse_search_replace_table(tsv);
        assert_eq!(total, 9);
        assert_eq!(changes.len(), 4);
        assert_eq!(changes[0].table, "wp_options");
        assert_eq!(changes[0].column, "option_value");
        assert_eq!(changes[0].count, 2);
        assert_eq!(changes[3].table, "wp_users");
        assert_eq!(changes[3].count, 1);
    }

    /// A zero-change dry run prints no table (wp-cli sends the "0 replacements"
    /// line to stderr, which `compose_run` drops) — that must read as 0, [].
    #[test]
    fn empty_output_is_zero_changes() {
        assert_eq!(parse_search_replace_table("").0, 0);
        assert!(parse_search_replace_table("   \n\n").1.is_empty());
    }

    /// Column positions come from the header, so a reordered/extra-column table
    /// still maps Replacements correctly and ignores unrelated columns.
    #[test]
    fn reads_columns_by_header_position() {
        let reordered = "\
+--------------+------------+---------------+
| Replacements | Table      | Column        |
+--------------+------------+---------------+
| 7            | wp_meta    | meta_value    |
+--------------+------------+---------------+";
        let (total, changes) = parse_search_replace_table(reordered);
        assert_eq!(total, 7);
        assert_eq!(changes[0].table, "wp_meta");
        assert_eq!(changes[0].column, "meta_value");
        assert_eq!(changes[0].count, 7);
    }
}
